name: bl
commands:
  - name: switchNpmrc
  - name: duCurrentFolder
  - name: calcTsPercentInProject
  - name: calcWorkingTime
  - name: gitDropVersion
  - name: gitCommit
  - name: detectCIStatus
  - name: gitReplacePackage
  - name: startZellij
  - name: generateShellCompletions
