name: bl
commands:
  - name: switchNpmrc
  - name: duCurrentFolder
  - name: calcTsPercentInProject
  - name: computeWorkingTime
  - name: gitDropVersion
  - name: gitCommit
  - name: detectCIStatus
  - name: mbGitReplacePackage
  - name: startZellij
