lastupdatecheck: 0
recentrepos:
    - /home/bl/df
    - /home/bl/prjs/blocksuite
    - /home/bl/.config/nvim
    - /home/bl/prjs/blurkit
    - /home/bl/df/config/.config/nvim
    - /home/bl/prjs/thelostdays
    - /home/bl/prjs/plantuml-parser
    - /home/bl/prjs/remesh
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
