#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#pkill compton
pkill picom
pkill nm-applet
pkill trayer
#pkill fcitx5
#pkill polybar
#pkill conky
#if [ -x "$(command -v eww)" ]; then
eww kill
#fi
